version: '3'
services:
  wordpress:
    build: .
    volumes:
    - .:/code
    - /tmp/awspricing:/tmp/awspricing
    environment:
      - AWSPRICING_USE_CACHE=1
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - USER
  ami:
    build: ./packer
