---
"Product Slug": "wordpress"
"Product ID": "f3bfa640-c230-4a34-9c4a-91d4a98f9a2e"
"Product Code": "efhxtk9jnp4yw8654eosytw6m"
"Accessibility": "Public"
"SKU": "OE_PATTERNS_WORDPRESS"
"Software by": "Ordinary Experts"
"Title": "Ordinary Experts WordPress Bedrock Pattern"
"Short Description": "The Ordinary Experts WordPress Bedrock Pattern is a custom AMI + open-source AWS CloudFormation template that provisions a production-ready, CICD-enabled AWS infrastructure solution for deploying WordPress Bedrock."
"Full Description": "The Ordinary Experts WordPress Bedrock Pattern is an open-source AWS CloudFormation template that offers an easy-to-install AWS infrastructure solution for quickly deploying a WordPress Bedrock project, using both AWS and WordPress best practices.

This template provides a base WordPress 6.2.2 Bedrock application or can be used with an existing WordPress Bedrock project. The solution creates a CodePipeline which automatically deploys new changes when an artifact is uploaded to S3. See our example WordPress site for how to bundle your code into S3.

Automatically configured to support auto-scaling through AWS Autoscaling Groups, this solution leverages an EFS file system to share user generated content between application servers.

The template ensure multi-level security by incorporating AWS IAM for federated access to resources with least privilege and AWS managed keys and Secret Manager to manage secrets for encryption of data at rest and in transit.

We support multiple availability zones using an RDS Aurora MySQL cluster and EC2 Auto Scaling Groups."
"Highlight1": "Production-ready CICD enabled WordPress Bedrock site."
"Highlight2": "Integrated with AWS Certificate Manager for HTTPS support."
"Highlight3": "Logs in CloudWatch Logs, Remote access via Session Manager."
"Product Category1": "Application Stacks"
"Product Category2": "Application Development"
"Product Category3": "Content Management"
"Search Keywords": "wordpress, bedrock, cms, open source"
"Resource1_Name": "Ordinary Experts Product Page"
"Resource1_URL": "https://ordinaryexperts.com/products/wordpress-pattern/"
"Resource2_Name": "Github Source Code and Documentation"
"Resource2_URL": "https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-wordpress/tree/main"
"Resource3_Name": "WordPress Bedrock Homepage"
"Resource3_URL": "https://roots.io/bedrock/"
"Image URL": "https://ordinaryexperts.com/img/products/wordpress-pattern/wordpress-product-logo.png"
"Product Video": ""
"Support Offered": "TRUE"
"Support Information": "https://ordinaryexperts.com/products/wordpress-pattern/"
"Support Detail": "Email support offered with subscription."
"Refund and Cancelation Policy": "We do not currently support refunds, but you can cancel at any time."
"Type": "AMI"
"us-east-1 AMI ID": "{{ami}}" # final ami id
"AMI Virtualization Type": "HVM"
"Architecture": "x86_64"
"AFI": ""
"Operating System": "UBUNTU"
"Operating System Version": "22.04"
"Operating System Username": "ubuntu"
"PIOPS Total": ""
"AWS Services Required": "EC2, VPC, IAM, SNS, CloudFormation, CloudWatch, CodePipeline, CodeDeploy, Lambda, S3, Route 53, Systems Manager"
"3rd Party Software Included": "Ubuntu packages: see GitHub, AWS CloudFormation utilities, AWS CLI, AWS CloudWatch agent."
"Version Title": "{{version}}"
"Release Notes": "See GitHub project for release notes."
"Upgrade Instructions": "Re-run the stack to apply new infrastructure changes."
"Product Access Instructions": "Run the stack. After Stack Completion, see CloudFormation Outputs for the URL of the provisioned WordPress site."
"Endpoint URL Protocol": "https"
"Endpoint URL Port": "443"
"Endpoint URL Relative URL": ""
"Countries to include": ""
"Countries to exclude": ""
# EULA: https://docs.aws.amazon.com/marketplace/latest/userguide/standardized-license-terms.html
"End User License Agreement URL": "https://s3.amazonaws.com/EULA/Standard+Contract+for+AWS+Marketplace+2019-04-24.pdf"
# region availability fields are here, i.e. "me-south-1 Availability"
"Make available in all future U.S. regions": "FALSE"
"Make available in all future non-U.S. regions": "FALSE"
"Recommended Instance Type": "m5.xlarge"
"Make available for all future instance types": "FALSE"
# instance availability fields are here, i.e. "z1d.12xlarge Availability"
"Pricing Model": "Hourly_Annual"
"Product Tax Code": "A_GEN_NOTAX"
"BYOL URL": ""
"Free Trial Instance Count": "1"
"Free Trial Duration": "5"
# instance Hourly Price fields are here, i.e. "z1d.12xlarge Hourly Price"
"Monthly Price": ""
# instance Annual Price fields are here, i.e. "z1d.12xlarge Annual Price"
"Security Group Rule 1": ""
"Security Group Rule 2": ""
"Security Group Rule 3": ""
"Security Group Rule 4": ""
"Security Group Rule 5": ""
"Security Group Rule 6": ""
"Security Group Rule 7": ""
"Security Group Rule 8": ""
"Security Group Rule 9": ""
"Security Group Rule 10": ""
"Security Group Rule 11": ""
"Security Group Rule 12": ""
"FCP Category": ""
"FCP Unit": ""
"FCP Dimension1 Name": ""
"FCP Dimension1 Description": ""
"FCP Dimension1 Rate": ""
"FCP Dimension2 Name": ""
"FCP Dimension2 Description": ""
"FCP Dimension2 Rate": ""
"FCP Dimension3 Name": ""
"FCP Dimension3 Description": ""
"FCP Dimension3 Rate": ""
"FCP Dimension4 Name": ""
"FCP Dimension4 Description": ""
"FCP Dimension4 Rate": ""
"FCP Dimension5 Name": ""
"FCP Dimension5 Description": ""
"FCP Dimension5 Rate": ""
"FCP Dimension6 Name": ""
"FCP Dimension6 Description": ""
"FCP Dimension6 Rate": ""
"FCP Dimension7 Name": ""
"FCP Dimension7 Description": ""
"FCP Dimension7 Rate": ""
"FCP Dimension8 Name": ""
"FCP Dimension8 Description": ""
"FCP Dimension8 Rate": ""
"FCP Dimension9 Name": ""
"FCP Dimension9 Description": ""
"FCP Dimension9 Rate": ""
"FCP Dimension10 Name": ""
"FCP Dimension10 Description": ""
"FCP Dimension10 Rate": ""
"FCP Dimension11 Name": ""
"FCP Dimension11 Description": ""
"FCP Dimension11 Rate": ""
"FCP Dimension12 Name": ""
"FCP Dimension12 Description": ""
"FCP Dimension12 Rate": ""
"FCP Dimension13 Name": ""
"FCP Dimension13 Description": ""
"FCP Dimension13 Rate": ""
"FCP Dimension14 Name": ""
"FCP Dimension14 Description": ""
"FCP Dimension14 Rate": ""
"FCP Dimension15 Name": ""
"FCP Dimension15 Description": ""
"FCP Dimension15 Rate": ""
"FCP Dimension16 Name": ""
"FCP Dimension16 Description": ""
"FCP Dimension16 Rate": ""
"FCP Dimension17 Name": ""
"FCP Dimension17 Description": ""
"FCP Dimension17 Rate": ""
"FCP Dimension18 Name": ""
"FCP Dimension18 Description": ""
"FCP Dimension18 Rate": ""
"FCP Dimension19 Name": ""
"FCP Dimension19 Description": ""
"FCP Dimension19 Rate": ""
"FCP Dimension20 Name": ""
"FCP Dimension20 Description": ""
"FCP Dimension20 Rate": ""
"FCP Dimension21 Name": ""
"FCP Dimension21 Description": ""
"FCP Dimension21 Rate": ""
"FCP Dimension22 Name": ""
"FCP Dimension22 Description": ""
"FCP Dimension22 Rate": ""
"FCP Dimension23 Name": ""
"FCP Dimension23 Description": ""
"FCP Dimension23 Rate": ""
"FCP Dimension24 Name": ""
"FCP Dimension24 Description": ""
"FCP Dimension24 Rate": ""
"Clusters and AWS Resources Topology 1: Title": "Ordinary Experts WordPress Bedrock Pattern"
"Clusters and AWS Resources Topology 1: AWS Calculator Link": "https://calculator.aws/#/estimate?id=035fd24f9bf0bcccd5298d023ed423ce9725a1a5"
"Clusters and AWS Resources Topology 1: Short Description": "The Ordinary Experts WordPress Bedrock Pattern is a custom AMI + open-source AWS CloudFormation template that provisions a production-ready, CICD-enabled AWS infrastructure solution for deploying WordPress Bedrock."
"Clusters and AWS Resources Topology 1: Long Description": "The Ordinary Experts WordPress Bedrock Pattern is an open-source AWS CloudFormation template that offers an easy-to-install AWS infrastructure solution for quickly deploying a WordPress Bedrock project, using both AWS and WordPress best practices.

This template provides a base WordPress Bedrock application or can be used with an existing WordPress Bedrock project. The solution creates a CodePipeline which automatically deploys new changes when an artifact is uploaded to S3. See our example WordPress site for how to bundle your code into S3.

Automatically configured to support auto-scaling through AWS Autoscaling Groups, this solution leverages an EFS file system to share user generated content between application servers.

The template ensure multi-level security by incorporating AWS IAM for federated access to resources with least privilege and AWS managed keys and Secret Manager to manage secrets for encryption of data at rest and in transit.

We support multiple availability zones using an RDS Aurora MySQL cluster and EC2 Auto Scaling Groups."
"Clusters and AWS Resources Topology 1: CloudFormation Template URL": "https://ordinary-experts-aws-marketplace-pattern-artifacts.s3.amazonaws.com/wordpress/{{version}}/template.yaml"
"Clusters and AWS Resources Topology 1: Architecture Diagram URL": "https://ordinaryexperts.com/img/products/wordpress-pattern/wordpress-architecture-diagram.png"
"Clusters and AWS Resources Topology 2: Title": ""
"Clusters and AWS Resources Topology 2: AWS Calculator Link": "None"
"Clusters and AWS Resources Topology 2: Short Description": ""
"Clusters and AWS Resources Topology 2: Long Description": ""
"Clusters and AWS Resources Topology 2: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 2: Architecture Diagram URL": ""
"Clusters and AWS Resources Topology 3: Title": ""
"Clusters and AWS Resources Topology 3: AWS Calculator Link": "None"
"Clusters and AWS Resources Topology 3: Short Description": ""
"Clusters and AWS Resources Topology 3: Long Description": ""
"Clusters and AWS Resources Topology 3: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 3: Architecture Diagram URL": ""
