version: 0.2

phases:
  build:
    commands:
      - |
        cat << EOF > after-install.sh;
        #!/bin/bash
        echo "$(date): Starting after-install.sh..."
        BASE_DEPLOY_DIR=\$(cat /opt/codedeploy-agent/deployment-root/deployment-instructions/*_last_successful_install)
        DEPLOY_DIR=\$BASE_DEPLOY_DIR/deployment-archive/
        chown -R www-data:www-data \$DEPLOY_DIR
        find \$DEPLOY_DIR -type d -exec chmod 755 {} +
        find \$DEPLOY_DIR -type f -exec chmod 644 {} +

        mkdir -p /var/www/app
        rsync -avzh --delete \$DEPLOY_DIR /var/www/app
        if [ ! -L /var/www/app/bedrock/web/app/uploads ]; then
          rm -rf /var/www/app/bedrock/web/app/uploads
          ln -s /mnt/efs/wordpress/uploads /var/www/app/bedrock/web/app/uploads
        fi
        service apache2 reload
        echo "$(date): Finished after-install.sh."
        EOF
        cat << EOF > appspec.yml;
        version: 0.0
        os: linux
        hooks:
          AfterInstall:
            - location: after-install.sh
              runas: root
        EOF
      - cat appspec.yml
      - cat after-install.sh
      - curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
      - php /tmp/composer-setup.php --install-dir=.
      - cd bedrock && ../composer.phar install
    finally:
      - echo Finished build
artifacts:
  files:
    - "**/*"
