version: 0.2

phases:
  build:
    commands:
      - |
        if [ ! -f appspec.yml ]; then
          cat << EOF > appspec.yml;
        version: 0.0
        os: linux
        files:
          - source: .
            destination: /var/www/app
        hooks:
        EOF
          mkdir -p scripts;
          if [ ! -f scripts/codedeploy-before-install.sh ]; then
            cat << EOF > scripts/codedeploy-before-install.sh;
        #!/bin/bash

        rm -f /var/www/app/wordpress/sites/default/files
        EOF
            cat << EOF >> appspec.yml;
          BeforeInstall:
            - location: scripts/codedeploy-before-install.sh
              runas: root
        EOF
          fi
          if [ ! -f scripts/codedeploy-after-install.sh ]; then
            cat << EOF > scripts/codedeploy-after-install.sh;
        #!/bin/bash

        # symlink to efs files directory
        ln -s /mnt/efs/wordpress/files /var/www/app/wordpress/sites/default/files

        # permissions
        find /var/www/app/wordpress -type d -exec chmod 755 {} +
        find /var/www/app/wordpress -type f -exec chmod 644 {} +
        chmod 444 /var/www/app/wordpress/.htaccess
        chmod 555 /var/www/app/wordpress/sites/default
        chmod 400 /var/www/app/wordpress/sites/default/settings.php
        find /var/www/app/wordpress/sites/default/files -type d -exec chmod 755 {} +
        find /var/www/app/wordpress/sites/default/files -type f -exec chmod 664 {} +
        chown -R www-data /var/www/app/wordpress
        EOF
            if [ -f wordpress/vendor/drush/drush/drush ]; then
              cat << EOF >> scripts/codedeploy-after-install.sh;

        # clear wordpress cache
        chmod 755 /var/www/app/wordpress/vendor/drush/drush/drush
        # recreate symlink: https://github.com/aws/aws-codedeploy-agent/issues/152
        rm /var/www/app/wordpress/vendor/bin/drush
        ln -s /var/www/app/wordpress/vendor/drush/drush/drush /var/www/app/wordpress/vendor/bin/drush
        chmod 755 /var/www/app/wordpress/vendor/bin/drush

        # only clear cache on "first" instance
        THIS_INSTANCE_ID=\$(curl http://169.254.169.254/latest/meta-data/instance-id)
        FIRST_ASG_INSTANCE_ID=\$(aws autoscaling describe-auto-scaling-instances \
          --query "AutoScalingInstances[?AutoScalingGroupName=='$AUTO_SCALING_GROUP_NAME']|[?LifecycleState=='InService']|[?HeathStatus=='HEALTHY']||[0].InstanceId" \
          --output text)
        if [ "\$FIRST_ASG_INSTANCE_ID" == "\$THIS_INSTANCE_ID" ];
        then
          export HOME=/var/www/app/wordpress
          cd /var/www/app/wordpress
          /var/www/app/wordpress/vendor/bin/drush cache:rebuild
          echo "Wordpress cache cleared by \$THIS_INSTANCE_ID" >> /var/log/wordpress-cache.log
        fi
        EOF
            fi
            cat << EOF >> appspec.yml;
          AfterInstall:
            - location: scripts/codedeploy-after-install.sh
              runas: root
        EOF
          fi
        fi
      - cat appspec.yml
      - cat scripts/codedeploy-before-install.sh
      - cat scripts/codedeploy-after-install.sh
    finally:
      - echo Finished build
artifacts:
  files:
    - "**/*"
